### signup
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email":"admin@m.com",
    "password":"123"
} 


### sigin in user 

POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email":"stttdddddest@m.com",
    "password":"123"
} 

### get the current user

GET http://localhost:3000/auth/whoami



### sginout

POST http://localhost:3000/auth/signout


### find user with id

GET http://localhost:3000/auth/3


### find add users with the email

GET http://localhost:3000/auth?email=stttest@m.com


### delete user with id 

DELETE http://localhost:3000/auth/2

### update user 

PATCH http://localhost:3000/auth/3
content-type: application/json


{
    "email":"tesgggt@m.com"
}